// src/content/unwriting/graph.ts
// Entry One: Unwriting. The key dependency graph — the game's actual
// structure. Pure data rendered by dumb screens; the engine computes
// attackability. Full design rationale + root-page specs: DESIGN.md and
// design/key-graph.html. test-graph.ts PROVES the doctrine claims (all 28
// reachable, 6 roots, instrument-blocked frontier = 13 incl. seal 25).

import type { KeyDef, KeyId, Page } from '../../models';

export const KEYS: Record<KeyId, KeyDef> = {
  W1: { kind: 'word', label: '1961' },
  W2: { kind: 'word', label: 'MAGPIE' },
  W3: { kind: 'word', label: 'THURSDAY' },
  W4: { kind: 'word', label: 'GREENHOUSE' },
  W5: { kind: 'word', label: 'JUNE 1974' },
  W6: { kind: 'word', label: 'NIGHTINGALE' },
  W7: { kind: 'word', label: '14 LARKSPUR' },
  W8: { kind: 'word', label: 'ROOM 214' },
  RAKING: { kind: 'instrument', label: 'Raking light' },
  UV: { kind: 'instrument', label: 'Ultraviolet' },
  SPECTRAL: { kind: 'instrument', label: 'Spectral view' },
  L1: { kind: 'letter', label: 'V → 1' },
  L2: { kind: 'letter', label: 'R → 13' },
  L3: { kind: 'letter', label: 'R → 8' },
  L4: { kind: 'letter', label: 'E → 12' },
  L5: { kind: 'letter', label: 'T → 7' },
  L6: { kind: 'letter', label: 'O → 5' },
  L7: { kind: 'letter', label: 'S → 6' },
  L8: { kind: 'letter', label: 'A → 4' },
  L9: { kind: 'letter', label: 'A → 9' },
  L10: { kind: 'letter', label: 'N → 10' },
  L11: { kind: 'letter', label: 'D → 11' },
  L12: { kind: 'letter', label: 'E → 2' },
  L13: { kind: 'letter', label: 'R → 3' },
  S1: { kind: 'seal', label: 'First seal' },
  S2: { kind: 'seal', label: 'Second seal' },
  S3: { kind: 'seal', label: 'Third seal' },
  S4: { kind: 'seal', label: 'Fourth seal' },
};

const ALL_LETTERS: KeyId[] = [
  'L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8', 'L9', 'L10', 'L11', 'L12', 'L13',
];

/** UI label for a key. Earned keys show their logged value (doctrine 7).
 *  Unearned instruments show their tool name (it's on the panel anyway).
 *  Everything else unearned is masked to its producing page — where a key
 *  comes from is rule-4 information; what it says is the puzzle (rule 15:
 *  the bench must never print an answer the player hasn't earned). */
export function keyLabel(k: KeyId, earned: ReadonlySet<KeyId>): string {
  if (earned.has(k) || KEYS[k].kind === 'instrument') return KEYS[k].label;
  const producer = PAGES.find((p) => p.produces.includes(k))!;
  return `key · p${String(producer.id).padStart(2, '0')}`;
}

export const PAGES: Page[] = [
  { id: 1, title: 'Accession', arc: 'intake', produces: ['W1'], consumes: [],
    mech: 'catalog cross-reference',
    story: 'The journal arrived in estate lot 44 with its flyleaf name cut out by blade.' },
  { id: 2, title: 'The Dedication', arc: 'intake', produces: ['W2'], consumes: [],
    mech: 'null cipher (OCR-confidence)',
    story: 'The whole book is addressed to someone she calls Magpie.' },
  { id: 3, title: 'Household Ledger', arc: 'intake', produces: ['W3'], consumes: [],
    mech: 'ledger anomaly',
    story: 'Every Thursday a withdrawal hides under the grocery entries — she is saving escape money.' },
  { id: 4, title: 'Calibration Plate I', arc: 'intake', produces: ['RAKING'], consumes: ['W1'],
    mech: 'geometric alignment (chain A taught)',
    story: 'She hand-drew a scanner calibration target decades before scanners existed; she knew this book would be scanned.' },
  { id: 5, title: 'Pressed Violets', arc: 'intake', produces: ['W4'], consumes: [],
    mech: 'floriography (paired-opposites selection)',
    story: 'The flowers come from the garden where she and her daughter were happiest; the garden no longer exists.' },
  { id: 6, title: 'The Photograph Corners', arc: 'intake', produces: ['W5'], consumes: ['RAKING'],
    mech: 'impression reading',
    story: 'Every photograph was removed, but raking light finds ghost impressions of their captions — first proof the damage is deliberate.' },
  { id: 7, title: 'Radio Log', arc: 'intake', produces: ['W6'], consumes: ['W3'],
    mech: 'dial mapping',
    story: 'Late at night she listens for one voice on the radio — her single remaining contact.' },
  { id: 8, title: 'Calibration Plate II', arc: 'intake', produces: ['UV'], consumes: ['W5'],
    mech: 'two-ink alignment (chain A twisted)',
    story: 'The second plate is drawn in two inks and one only exists under UV: half this book is written in invisible ink.' },
  { id: 9, title: 'Margin Arithmetic', arc: 'intake', produces: ['W7'], consumes: ['W2', 'W4'],
    mech: 'modular arithmetic',
    story: 'The sums in the margins are her counting what leaving the house will cost.' },
  { id: 10, title: 'The Unfiled Form', arc: 'recovery', produces: ['L1', 'W8'], consumes: ['UV'],
    mech: 'forgery deduction',
    story: 'A change-of-address filed in her name, in handwriting that is not hers: how he moved her world without touching her.' },
  { id: 11, title: 'Carbon Paper', arc: 'recovery', produces: ['L2'], consumes: [],
    mech: 'mirror reconstruction',
    story: "A carbon sheet preserves her letter requesting her own records — denied: 'requester could not be verified.'" },
  { id: 12, title: "The Notary's Stamp", arc: 'recovery', produces: ['L3'], consumes: ['W6'],
    mech: 'fragment reassembly + symbol key',
    story: 'Nightingale is a notary — the friend who helped her use paperwork to unmake paperwork.' },
  { id: 13, title: 'Redaction Practice', arc: 'recovery', produces: ['L4'], consumes: ['RAKING'],
    mech: 'redaction metrology',
    story: 'She practiced erasure like calligraphy: trial blackouts, each labeled with what it hides.' },
  { id: 14, title: 'Marriage Certificate', arc: 'recovery', produces: ['L5'], consumes: ['W5', 'UV'],
    mech: 'ink-bleed physics',
    story: "June 1974, the wedding — and in the margin: 'the first form he ever filed for me.'" },
  { id: 15, title: "The Locksmith's Receipt", arc: 'recovery', produces: ['L6'], consumes: ['W7'],
    mech: 'key-bitting code',
    story: 'She changed the locks three times in a year; he always had a key within the week, requested through the county.' },
  { id: 16, title: 'Library Slip', arc: 'recovery', produces: ['L7'], consumes: [],
    mech: 'date-interval cipher',
    story: 'Her borrowing record on disappearing: privacy law, bookbinding, the chemistry of ink — and a librarian who never reported her overdue.' },
  { id: 17, title: 'Spectral Pair', arc: 'recovery', produces: ['SPECTRAL'], consumes: ['W8', 'UV'],
    mech: 'delta collation (chain B taught)',
    story: 'She wrote the same entry twice, once true and once cover story, to teach the machine to tell them apart.' },
  { id: 18, title: "The Daughter's Drawing", arc: 'recovery', produces: ['L8'], consumes: ['SPECTRAL'],
    mech: 'channel-separation tracing',
    story: 'Under the crayon greenhouse, spectral separation finds the daughter’s new surname — the adoption that kept her unfindable.' },
  { id: 19, title: 'Bus Timetable', arc: 'recovery', produces: ['L9'], consumes: ['W6'],
    mech: 'timetable logic',
    story: 'The night route passes the greenhouse; she rode it for years and never once got off.' },
  { id: 20, title: 'The Interview', arc: 'recovery', produces: ['L10'], consumes: ['SPECTRAL', 'W2'],
    mech: 'planted-error harvest',
    story: 'The only photograph of her ever printed is half out of frame, and the misspelled caption was her own doing.' },
  { id: 21, title: 'Inventory of the Lost', arc: 'recovery', produces: ['L11'],
    consumes: ['RAKING', 'UV', 'SPECTRAL'],
    mech: 'tri-layer interleave',
    story: 'A list in three inks of everything she destroyed: what it was, where it was, why it hurt.' },
  { id: 22, title: 'First Day', arc: 'recovery', produces: ['L12'], consumes: ['W4'],
    mech: 'pinprick code',
    story: "Age nineteen, first day at the archive: 'I wanted to be the one who decides what is remembered.'" },
  { id: 23, title: 'The Blank Census', arc: 'recovery', produces: ['L13'], consumes: ['W8'],
    mech: 'census-grid constraint deduction',
    story: 'The scraped-out line in her childhood census is not hers — it is her father’s, and her mother held the blade.' },
  { id: 24, title: 'First Check: The Name You Answered To', arc: 'signature', produces: ['S1'],
    consumes: ['W2', 'L8'],
    mech: 'grille overlay',
    story: "'If you are Magpie, you kept the drawing.'" },
  { id: 25, title: 'Second Check: The Route Home', arc: 'signature', produces: ['S2'],
    consumes: ['W7', 'L6', 'L9'],
    mech: 'cartographic trace',
    story: 'Only someone who rode the route knows where it truly stops.' },
  { id: 26, title: 'Third Check: The Two Truths', arc: 'signature', produces: ['S3'],
    consumes: ['SPECTRAL', 'L5', 'L10'],
    mech: 'delta collation (chain B mastered)',
    story: "'He believed everything that was written down. Show me you don’t.'" },
  { id: 27, title: 'Fourth Check: What She Taught', arc: 'signature', produces: ['S4'],
    consumes: ['W6', 'L12', 'L13', 'RAKING', 'UV'],
    mech: 'nested composite',
    story: "The last lesson is addressed 'to whoever you are, now that you have come this far' — she knew it might not be Magpie." },
  { id: 28, title: 'The Last Signature', arc: 'signature', produces: [],
    consumes: ['S1', 'S2', 'S3', 'S4', ...ALL_LETTERS],
    mech: 'the signature is a choice, not a puzzle',
    story: 'Where you enter her name decides everything: the archive record, the delivery search, or the shredder routine.' },
];
